<?php

return [
    'romantik' => [
        'emoji' => '🎭',
        'label' => 'Romantik',
        'description' => 'Aşk dolu hikayeler',
        'genres' => [10749],
        'tv_genres' => [18, 35],
        'gradient' => 'from-pink-500 to-rose-600',
    ],
    'macera' => [
        'emoji' => '🏔️',
        'label' => 'Macera',
        'description' => 'Keşif ve heyecan dolu',
        'genres' => [12],
        'tv_genres' => [10759],
        'gradient' => 'from-emerald-500 to-teal-600',
    ],
    'komedi' => [
        'emoji' => '😂',
        'label' => 'Komedi',
        'description' => 'Kahkaha garantili',
        'genres' => [35],
        'tv_genres' => [35],
        'gradient' => 'from-yellow-400 to-orange-500',
    ],
    'gerilim' => [
        'emoji' => '😱',
        'label' => 'Gerilim',
        'description' => 'Nefesini tut',
        'genres' => [53, 27],
        'tv_genres' => [80, 9648],
        'gradient' => 'from-red-600 to-purple-700',
    ],
    'bilimkurgu' => [
        'emoji' => '🚀',
        'label' => 'Bilim Kurgu',
        'description' => 'Geleceğe yolculuk',
        'genres' => [878],
        'tv_genres' => [10765],
        'gradient' => 'from-indigo-500 to-blue-700',
    ],
    'dram' => [
        'emoji' => '🎬',
        'label' => 'Dram',
        'description' => 'Derin ve etkileyici',
        'genres' => [18],
        'tv_genres' => [18],
        'gradient' => 'from-gray-600 to-gray-800',
    ],
    'gizem' => [
        'emoji' => '🔍',
        'label' => 'Gizem',
        'description' => 'Çözülmeyi bekleyen sırlar',
        'genres' => [9648],
        'tv_genres' => [9648, 80],
        'gradient' => 'from-violet-600 to-indigo-800',
    ],
    'muzikal' => [
        'emoji' => '🎶',
        'label' => 'Müzikal',
        'description' => 'Müzik ve dans dolu',
        'genres' => [10402],
        'tv_genres' => [35, 18],
        'gradient' => 'from-fuchsia-500 to-pink-700',
    ],
    'aile' => [
        'emoji' => '👨‍👩‍👧‍👦',
        'label' => 'Aile',
        'description' => 'Her yaşa uygun',
        'genres' => [10751],
        'tv_genres' => [10751, 16],
        'gradient' => 'from-sky-400 to-cyan-600',
    ],
    'aksiyon' => [
        'emoji' => '💥',
        'label' => 'Aksiyon',
        'description' => 'Adrenalin dolu',
        'genres' => [28],
        'tv_genres' => [10759],
        'gradient' => 'from-orange-500 to-red-600',
    ],
    '+18' => [
        'emoji' => '🔞',
        'label' => '+18 Yetişkin',
        'description' => 'Sadece yetişkinler',
        'genres' => [],
        'tv_genres' => [],
        'gradient' => 'from-red-800 to-gray-900',
        'adult' => true,
        'keywords' => '1907,965,8233,4379,4434,6149',
    ],
    'turk' => [
        'emoji' => '🇹🇷',
        'label' => 'Türk Yapımları',
        'description' => 'Yerli film ve diziler',
        'genres' => [],
        'tv_genres' => [],
        'gradient' => 'from-red-500 to-white/10',
        'origin_country' => 'TR',
    ],
];
